### ISSUE TITLE
Test everything in a Hellman-like environment(e.g. a sandbox cluster based on our setup)

### ISSUE THREAD

**Issue by SEQUOIIA** [dfds/provider-confluent#15]
- [ ] Spin up an EKS sandbox cluster (or use a pre-existing one), make sure it is on the very latest infrastructure-modules version
- [ ] Try to deploy provider-confluent to sandbox cluster
- [ ] Deploy a ProviderConfig for provider-confluent & test it with provider-confluent resources, say a Topic.

This assumes that you already have Crossplane installed in the used sandbox cluster. That should be the case, if it is up-to-date.

Crossplane Provider object:
```yaml
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-confluent
spec:
  package: dfdsdk/provider-confluent:latest
  ignoreCrossplaneConstraints: true
  packagePullPolicy: Always
```
